.\" Manpage for chonosEmbeddedMAS.
.\" Contact chon@grupo.cefet-rj.br.
.TH man 8 "25 Apr 2023" "1.2" "chonosEmbeddedMAS man page"

.SH NAME
chonosEmbeddedMAS \- ChonOS Embedded Multi-agent System Manager

.SH DESCRIPTION
A manager of the jasonEmbedded Multi-agent Systems.

List of options and arguments:

--import    \- imports a MAS2J Project.

--start     \- starts the Embedded MAS.

--stop      \- stops the Embedded MAS.

-f [file]   \- defines the MAS project file.

-m [value]  \- defines how much heap memory (in MB) will be allocated to the Embedded MAS. 
                By default, it will be allocated between 256 MB and 1024 MB. 
                This option adjusts the performance of the Embedded MAS.

.SH EXAMPLES
chonosEmbeddedMAS --import -f /home/user/MAS2Jproject.zip
    Imports the .ZIP file from the MAS2J Project.

chonosEmbeddedMAS --start
    Executes the MAS2J Project previously imported. 

chonosEmbeddedMAS --start -m 512
    Executes the MAS2J Project previously imported and allocates 512 MB for heap memory. 

.SH REPORTING BUGS
Research Group in Cognitive Hardware On Networks: chon@grupo.cefet-rj.br

.SH COPYRIGHT
Copyright © 2024 Chon Group <https://github.com/chon-group/jasonEmbedded>. 
